In [7]:
import yfinance as yf

test_data = yf.download("BTC-USD", period="5d", interval="1h")
test_data.head()

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Datetime,,,,,
2026-04-04 00:00:00+00:00,66882.726562,66939.015625,66881.312500,66937.250000,0
2026-04-04 01:00:00+00:00,66842.945312,66904.328125,66822.015625,66884.554688,0
2026-04-04 02:00:00+00:00,66811.125000,66903.179688,66803.226562,66845.085938,0
2026-04-04 03:00:00+00:00,66821.406250,66893.453125,66821.406250,66825.406250,0
2026-04-04 04:00:00+00:00,66858.101562,66858.125000,66790.789062,66826.062500,0

In [8]:
test_data.columns = test_data.columns.get_level_values(0)
test_data.head()

Price,Close,High,Low,Open,Volume
Datetime,,,,,
2026-04-04 00:00:00+00:00,66882.726562,66939.015625,66881.312500,66937.250000,0
2026-04-04 01:00:00+00:00,66842.945312,66904.328125,66822.015625,66884.554688,0
2026-04-04 02:00:00+00:00,66811.125000,66903.179688,66803.226562,66845.085938,0
2026-04-04 03:00:00+00:00,66821.406250,66893.453125,66821.406250,66825.406250,0
2026-04-04 04:00:00+00:00,66858.101562,66858.125000,66790.789062,66826.062500,0

In [9]:
import pandas_ta as ta

test_data["SMA_20"] = ta.sma(test_data.ta.sma(close=test_data["Close"], length=20))

test_data.tail()

Price,Close,High,Low,Open,Volume,SMA_20
Datetime,,,,,,
2026-04-07 23:00:00+00:00,71926.757812,72694.312500,71232.070312,71482.601562,3789967360,68673.166133
2026-04-08 00:00:00+00:00,71675.898438,72057.078125,71556.203125,71926.156250,1314430976,68704.415664
2026-04-08 01:00:00+00:00,71457.945312,71729.000000,71454.523438,71688.789062,165175296,68757.646992
2026-04-08 02:00:00+00:00,71323.601562,71700.562500,71270.164062,71526.929688,903651328,68832.812305
2026-04-08 03:00:00+00:00,71386.960938,71438.203125,71273.445312,71361.906250,106119168,68925.822578

In [10]:
test_data["RSI_14"] = test_data.ta.rsi(close=test_data["Close"], length=14)
test_data.tail()

Price,Close,High,Low,Open,Volume,SMA_20,RSI_14
Datetime,,,,,,,
2026-04-07 23:00:00+00:00,71926.757812,72694.312500,71232.070312,71482.601562,3789967360,68673.166133,77.174277
2026-04-08 00:00:00+00:00,71675.898438,72057.078125,71556.203125,71926.156250,1314430976,68704.415664,73.524541
2026-04-08 01:00:00+00:00,71457.945312,71729.000000,71454.523438,71688.789062,165175296,68757.646992,70.408993
2026-04-08 02:00:00+00:00,71323.601562,71700.562500,71270.164062,71526.929688,903651328,68832.812305,68.482702
2026-04-08 03:00:00+00:00,71386.960938,71438.203125,71273.445312,71361.906250,106119168,68925.822578,68.914646

In [15]:
ticker = "BTC-USD"

df = yf.download(ticker, period='60d', interval='1h')

df.columns = df.columns.get_level_values(0)

df.head()

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Datetime,,,,,
2026-02-08 00:00:00+00:00,68980.015625,69356.890625,68852.898438,69302.406250,0
2026-02-08 01:00:00+00:00,69318.828125,69422.046875,69075.101562,69090.867188,0
2026-02-08 02:00:00+00:00,69280.210938,69629.640625,69150.921875,69346.351562,0
2026-02-08 03:00:00+00:00,69053.335938,69367.515625,69033.835938,69326.210938,0
2026-02-08 04:00:00+00:00,69227.820312,69263.117188,68951.570312,69061.484375,0