In [100]:
import yfinance as yf

test_data = yf.download("BTC-USD", period="5d", interval="1h")
test_data.head()

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Datetime,,,,,
2026-04-06 00:00:00+00:00,69076.710938,69491.648438,68978.914062,68978.914062,233707520
2026-04-06 01:00:00+00:00,68801.539062,69076.625000,68782.648438,69063.718750,1045952512
2026-04-06 02:00:00+00:00,69227.781250,69365.109375,68780.351562,68780.351562,1052841984
2026-04-06 03:00:00+00:00,69061.843750,69217.367188,69044.992188,69207.960938,780525568
2026-04-06 04:00:00+00:00,69115.718750,69173.921875,68963.085938,69082.078125,800897024

In [101]:
test_data.columns = test_data.columns.get_level_values(0)
test_data.head()

Price,Close,High,Low,Open,Volume
Datetime,,,,,
2026-04-06 00:00:00+00:00,69076.710938,69491.648438,68978.914062,68978.914062,233707520
2026-04-06 01:00:00+00:00,68801.539062,69076.625000,68782.648438,69063.718750,1045952512
2026-04-06 02:00:00+00:00,69227.781250,69365.109375,68780.351562,68780.351562,1052841984
2026-04-06 03:00:00+00:00,69061.843750,69217.367188,69044.992188,69207.960938,780525568
2026-04-06 04:00:00+00:00,69115.718750,69173.921875,68963.085938,69082.078125,800897024

In [102]:
import pandas_ta as ta

test_data["SMA_20"] = ta.sma(test_data.ta.sma(close=test_data["Close"], length=20))

test_data.tail()

Price,Close,High,Low,Open,Volume,SMA_20
Datetime,,,,,,
2026-04-09 23:00:00+00:00,71771.632812,72000.117188,71637.812500,71962.484375,606830592,71317.682539
2026-04-10 00:00:00+00:00,71907.890625,72004.929688,71609.296875,71783.515625,271847424,71366.755625
2026-04-10 01:00:00+00:00,72172.648438,72347.562500,71730.296875,71932.625000,432549888,71417.817695
2026-04-10 02:00:00+00:00,71953.851562,72257.531250,71928.195312,72177.359375,335323136,71470.298555
2026-04-10 03:00:00+00:00,71955.875000,71961.484375,71955.875000,71961.484375,143360,71523.852188

In [103]:
test_data["RSI_14"] = test_data.ta.rsi(close=test_data["Close"], length=14)
test_data.tail()

Price,Close,High,Low,Open,Volume,SMA_20,RSI_14
Datetime,,,,,,,
2026-04-09 23:00:00+00:00,71771.632812,72000.117188,71637.812500,71962.484375,606830592,71317.682539,52.884846
2026-04-10 00:00:00+00:00,71907.890625,72004.929688,71609.296875,71783.515625,271847424,71366.755625,54.670211
2026-04-10 01:00:00+00:00,72172.648438,72347.562500,71730.296875,71932.625000,432549888,71417.817695,58.000505
2026-04-10 02:00:00+00:00,71953.851562,72257.531250,71928.195312,72177.359375,335323136,71470.298555,54.440905
2026-04-10 03:00:00+00:00,71955.875000,71961.484375,71955.875000,71961.484375,143360,71523.852188,54.468735

In [104]:
ticker = "BTC-USD"

df = yf.download(ticker, period='60d', interval='1h')

df.columns = df.columns.get_level_values(0)

df.head()

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Datetime,,,,,
2026-02-10 00:00:00+00:00,69837.250000,70204.343750,69722.859375,70109.421875,0
2026-02-10 01:00:00+00:00,70357.906250,70449.851562,69792.757812,69828.843750,0
2026-02-10 02:00:00+00:00,70051.406250,70398.859375,70007.968750,70398.859375,0
2026-02-10 03:00:00+00:00,69443.593750,70107.414062,69226.500000,70062.734375,0
2026-02-10 04:00:00+00:00,69804.070312,69831.414062,69511.515625,69527.445312,0

In [105]:
import yfinance as yf
import pandas_ta as ta
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [106]:
df = yf.download("BTC-USD", period="2y", interval="1h")

df.columns = df.columns.get_level_values(0)

[*********************100%***********************]  1 of 1 completed

In [107]:
df['SMA_20'] = ta.sma(df['Close'], length=20)
df['RSI_14'] = ta.rsi(df['Close'], length=14)

In [108]:
bbands = ta.bbands(df['Close'], length=20, std=2)
df['BBL'] = bbands.iloc[:, 0]
df['BBM'] = bbands.iloc[:, 1]
df['BBU'] = bbands.iloc[:, 2]

In [109]:
df['MACD'] = ta.macd(df['Close'])['MACD_12_26_9']
df['EMA_50'] = ta.ema(df['Close'], length=50)
df['ATR'] = ta.atr(df['High'], df['Low'], df['Close'])
df['OBV'] = ta.obv(df['Close'], df['Volume'])
df['VWAP'] = ta.vwap(df['High'], df['Low'], 
                      df['Close'], df['Volume'])

In [110]:
df['Price_Change'] = df['Close'].pct_change()
df['High_Low_Range'] = df['High'] - df['Low']
df['Volume_Change'] = df['Volume'].pct_change()

In [111]:
df['EMA_12'] = ta.ema(df['Close'], length=12)
df['EMA_26'] = ta.ema(df['Close'], length=26)
df['Momentum'] = df['Close'] - df['Close'].shift(4)
df['Volatility'] = df['Close'].rolling(10).std()

df['EMA_diff'] = df['EMA_12'] - df['EMA_26']
df['Close_to_SMA'] = df['Close'] / df['SMA_20'] - 1


df['BB_width'] = df['BBU'] - df['BBL']
df['SMA_diff'] = df['Close'] - df['SMA_20']

In [112]:
df['Target'] = (
    df['Close'].shift(-1) > df['Close'] * 1.001
).astype(int)

In [113]:
df.dropna(inplace=True)
X = df[[
    'Close', 'SMA_20', 'RSI_14',
    'BBL', 'BBM', 'BBU', 'BB_width',
    'High_Low_Range', 'Volume_Change',
    'EMA_12', 'EMA_26', 'EMA_diff',
    'Momentum', 'Volatility', 'SMA_diff',
    'Close_to_SMA', 'Price_Change',
    'EMA_50', 'MACD', 'ATR', 'OBV', 'VWAP'
]]
y = df['Target']

In [114]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [115]:
len(X_train)

8894

In [116]:
len(y_test)

2224

In [117]:
import xgboost as xgb
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.5,
    reg_alpha=0.1,
    reg_lambda=1,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

X_train_clean = X_train.replace([np.inf, -np.inf], np.nan)
X_test_clean = X_test.replace([np.inf, -np.inf], np.nan)

fill_values = X_train_clean.median()
X_train_clean = X_train_clean.fillna(fill_values)
X_test_clean = X_test_clean.fillna(fill_values)

y_train_clean = y_train.loc[X_train_clean.index]
y_test_clean = y_test.loc[X_test_clean.index]

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('xgb', model)
])

pipeline.fit(X_train_clean, y_train_clean)

y_pred = pipeline.predict(X_test_clean)
accuracy = accuracy_score(y_test_clean, y_pred)

print(f'Accuracy: {accuracy:.4%}')
print('Majority class baseline:', y_test_clean.value_counts(normalize=True).max())
print('Target distribution:', y_test_clean.value_counts(normalize=True).to_dict())
print(classification_report(y_test_clean, y_pred))
print(confusion_matrix(y_test_clean, y_pred))



y_train_clean = y_train.loc[X_train_clean.index]
accuracy = accuracy_score(y_test_clean, y_pred)
y_test_clean = y_test.loc[X_test_clean.index]
y_pred = pipeline.predict(X_test_clean)


pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('xgb', model)
])


    ('xgb', model)])    ('xgb', model)])

IndentationError: unexpected indent (1188381094.py, line 61)

In [ ]:
joblib.dump(model, 'aether_model.pkl')

['aether_model.pkl']